@startuml TTT activity plan
    repeat 
    :The board is Renderd;
    :A square is clicked;
    if (The square is taken or \n there has been a winner) then (yes)
    :End;
    end
    else (no)
        if (The board is full) then (yes)
        :End;
        end
        else (no)
        :Place current player in the square;
        :Render the updated Board;
    :start again;
@enduml