@startuml
    User->Front_end: Allows the user to login or create a username
    Front_end->Back_end: Adds or check the user in the database
    Front_end<-Back_end: Responds with what has been done
    User<-Front_end: Welcomes the user
    User->Front_end: Starts the game 
    User<-Front_end: Displays the game allowing the user to play
    User->Front_end: Plays the game until there's a winner
    Front_end->Back_end: Updates the database with the new stats
    Front_end<-Back_end: Sends the new stats to the front end
    User<-Front_end: displays the new stats to the user
@enduml